MMBlog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('post.urls')),
    path('tinymce/', include('tinymce.urls')),
    url(r'^api-auth/', include('rest_framework.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register/', views.Registration.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('profile/<int:pk>', views.UpdateProfile.as_view(), name='profile'),
]

post/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import *

from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers


# import domyślnych widoków na potrzeby logowania
from django.contrib.auth import views as auth_views


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
# router.register(r'chats', PostViewSet)
router.register(r'post/', PostViewSet, basename='Post')
router.register(r'comment/', CommentViewSet, basename='Comment')

app_name = 'post'
urlpatterns = [
                  url(r'api/', include(router.urls)),
                  path("add/", PostCreateView.as_view(), name="post_add"),
                  path("edit/<int:pk>/", PostEditView.as_view(), name="post_edit"),
                  path("del/<int:pk>/", PostDelView.as_view(), name="post_del"),
                  path("add_comment/<int:pk>", AddCommentAjax.as_view(), name="add_comment"),
                  path("detail/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
                  path("", PostListView.as_view(), name="post_list"),
                  path("search/", SearchResultsView.as_view(), name="search_post"),
                  path('by_tag/<slug:tag_slug>/', PostsByTag.as_view(), name='posts_by_tag'),
                  path('comment/<int:pk>/hide/', hide_comment, name='hide_comment'),
                  path('my_posts/', MyPostsView.as_view(), name='my_posts'),
                  path('most_commented_posts/', MostCommentedPostsView.as_view(), name='most_commented_posts'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_images')

    def __str__(self):
        return f"{self.user.username} profile"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        image = Image.open(self.image.path)
        if image.height > 400 or image.width > 400:
            output_size = (400, 400)
            image.thumbnail(output_size)
            image.save(self.image.path)

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Profile


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', ]

account/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from .forms import UserRegistrationForm, ProfileUpdateForm
from .models import Profile


class Registration(CreateView):
    form_class = UserRegistrationForm
    success_url = reverse_lazy('login')
    template_name = 'account/register.html'


class UpdateProfile(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Profile
    form_class = ProfileUpdateForm
    success_url = reverse_lazy('post:post_list')
    template_name = 'account/profile.html'
    success_message = 'Your profile has been updated'

account/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

{#    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>#}
{#    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>#}
{#    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>#}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'account/style.css' %}">

    <title>{% block title %}{% endblock %}</title>
    {{ form.media }}
</head>

<body>
    <header class="site-header">

      <nav class="navbar navbar-expand-lg navbar-dark bg-steel fixed-top">

        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'post:post_list' %}">M&M Blog</a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarToggle">

            <div class="navbar-nav mr-auto">
            {% if request.user == post.author %}
            <button class="btn btn-success mr-2" type="button" onclick="window.location.href='{% url 'post:post_edit' post.pk %}'">Post edit</button>
            <button class="btn btn-danger mr-2" type="button" onclick="window.location.href='{% url 'post:post_del' post.pk %}'">Delete post</button>
            {% endif %}
            </div>
              <form class="form-inline" method="GET" action="{% url 'post:search_post' %}">
                <input class="form-control mr-sm-2" name='q' value='{{ request.GET.q }}' type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success mr-5 my-2 my-sm-0" type="submit" >Search</button>
              </form>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'post:post_add' %}">Add New Post</a>
                    <a class="nav-item nav-link" href="{% url 'profile' user.profile.pk %}">{{ user.username }} profile</a>
                    <a class="nav-item nav-link" href="{% url 'password_change' %}">Password change</a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}
            </div>
          </div>

        </div>

      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">

        <div class="col-md-3">
          <p class="content-section">

              <ul class="list-group">
                {% if user.is_authenticated %}
                <li class="list-group-item list-group-item-light"><a href="{% url 'post:my_posts' %}">My Posts</a></li>
                {% else %}
                <li class="list-group-item list-group-item-light disabled"><a href="#">My Posts</a></li>
                {% endif %}
                <li class="list-group-item list-group-item-light"><a href="{% url 'post:most_commented_posts' %}">5 Most commented posts</a></li>
                <li class="list-group-item list-group-item-light"><a href="{% url 'post:post_list' %}">Latest posts</a></li>
                <li class="list-group-item list-group-item-light">Something else</li>

                    <div class="btn-group" role="group">
                    <button id="btnGroupDrop1" type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-offset="40,15">
                    List of Tags
                    </button>
                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                        {% for tag in tags %}
                            <li class="dropdown-item"><a href="{% url 'post:posts_by_tag' tag.slug %}">{{ tag.name }}</a></li>
                        {% endfor %}
                    </div>
                    </div>
              </ul>
          </div>
          <div class="col-md-9">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
          {% block content %}{% endblock %}
          </div>
        </div>
    </main>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

{% block javascript %}{% endblock %}
</body>
</html>