MMBlog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('post.urls')),
    path('tinymce/', include('tinymce.urls')),
    url(r'^api-auth/', include('rest_framework.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import *

from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers


# import domyślnych widoków na potrzeby logowania
from django.contrib.auth import views as auth_views


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
# router.register(r'chats', PostViewSet)
router.register(r'post/', PostViewSet, basename='Post')
router.register(r'comment/', CommentViewSet, basename='Comment')

app_name = 'post'
urlpatterns = [
                  url(r'api/', include(router.urls)),
                  path("add/", PostCreateView.as_view(), name="post_add"),
                  path("edit/<int:pk>/", PostEditView.as_view(), name="post_edit"),
                  path("del/<int:pk>/", PostDelView.as_view(), name="post_del"),
                  path("add_comment/<int:pk>", AddCommentAjax.as_view(), name="add_comment"),
                  path("detail/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
                  path("", PostListView.as_view(), name="post_list"),
                  path("search/", SearchResultsView.as_view(), name="search_post"),
                  path('by_tag/<slug:tag_slug>/', PostsByTag.as_view(), name='posts_by_tag'),
                  path('comment/<int:pk>/hide/', hide_comment, name='hide_comment'),
                  path('my_posts/', MyPostsView.as_view(), name='my_posts'),
                  path('most_commented_posts/', MostCommentedPostsView.as_view(), name='most_commented_posts'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from account.models import Profile

from taggit.managers import TaggableManager


class Post(models.Model):
    title = models.CharField(max_length=300, verbose_name="Title")
    body = models.TextField(default="", verbose_name="Details")
    created = models.DateTimeField(editable=False, default=timezone.now)
    modified = models.DateTimeField(auto_now=True, editable=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Username")
    image = models.ImageField(upload_to='blog_images/', null=True, blank=True, verbose_name="Add picture")
    tags = TaggableManager()

    def __str__(self):
        return f"Title: {self.title} writen by {self.author}"


class GoodCommentManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(hidden=False)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    author = models.CharField(max_length=150, default='Anonymous user')
    date_added = models.DateTimeField(auto_now_add=True)
    hidden = models.BooleanField(default=False)
    objects = models.Manager()
    good_comment = GoodCommentManager()

    class Meta:
        ordering = '-date_added',

    def hide_comment(self):
        self.hidden = True
        self.save()

post/forms.py
from .models import *
from django import forms

from tinymce.widgets import TinyMCE


class PostForm(forms.ModelForm):
    body = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30, 'nowrap': True}))

    class Meta:
        model = Post
        fields = ['title', 'tags', 'body', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text')

post/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core import serializers as django_serializers

from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import redirect, get_object_or_404

from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView

from django.contrib import messages
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormMixin

from .models import Post

from taggit.models import Tag

from .forms import *

from rest_framework import viewsets, serializers as rf_serializers


class PostCreateView(LoginRequiredMixin, CreateView, SuccessMessageMixin):
    form_class = PostForm
    template_name = 'post/post-add.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        post = Post.objects.filter(author=self.request.user).order_by('-created')[0]
        messages.add_message(self.request, messages.INFO, 'Post was crated')
        return reverse_lazy('post:post_detail', kwargs={'pk': post.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all().order_by('name')
        return context


class PostEditView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    form_class = PostForm
    template_name = 'post/post-edit.html'
    success_url = reverse_lazy('post:post_list')
    success_message = "Changes saved"
    queryset = Post.objects.all()

    def get_object(self, **kwargs):
        pk_ = self.kwargs.get("pk")
        return get_object_or_404(Post, pk=pk_)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all().order_by('name')
        return context


class PostDelView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, DeleteView):
    form_class = PostForm
    success_url = reverse_lazy('post:post_list')
    template_name = "post/post-del.html"

    def get_object(self, **kwargs):
        pk_ = self.kwargs.get("pk")
        return get_object_or_404(Post, pk=pk_)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all().order_by('name')
        return context

    def get_success_url(self, **kwargs):
        messages.add_message(self.request, messages.INFO, 'Post was deleted')
        return reverse_lazy('post:post_list')


class PostDetailDisplay(DetailView):
    template_name = 'post/post-detail.html'
    queryset = Post.objects.all()

    def get_object(self, **kwargs):
        pk_ = self.kwargs.get("pk")
        return get_object_or_404(Post, pk=pk_)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all().order_by('name')
        context['form'] = CommentForm
        return context


class AddCommentAjax(View):
    form = CommentForm
    template_name = 'post/post_detail.html'

    def post(self, *args, **kwargs):
        post = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        if self.request.is_ajax and self.request.method == 'POST':
            form = self.form(self.request.POST)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.post = post
                instance.save()
                serialized_instance = django_serializers.serialize('json', [instance, ])
                return JsonResponse({'instance': serialized_instance}, status=200)
            else:
                return JsonResponse({'instance': self.form.errors}, status=400)
        return JsonResponse({'instance': ''}, status=400)


class PostDetailView(FormMixin, DetailView):
    model = Post
    form_class = CommentForm()
    template_name = 'post/post-detail.html'

    def get(self, request, *args, **kwargs):
        view = PostDetailDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = AddCommentAjax.as_view()
        return view(request, *args, **kwargs)


class PostListView(ListView):
    paginate_by = 5
    model = Post
    template_name = 'post/post-list.html'
    ordering = '-created'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all()
        context['tags'] = Tag.objects.all().order_by('name')
        return context


class SearchResultsView(ListView):
    model = Post
    template_name = 'post/search-post.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Post.objects.filter(
            Q(title__icontains=query) | Q(author__username__icontains=query)
        )
        object_set = set(object_list)
        return object_set

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all().order_by('name')
        return context


def hide_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = get_object_or_404(Post, pk=comment.post.pk)
    if request.user == post.author:
        comment.hide_comment()
        return redirect('post:post_detail', pk=comment.post.pk)


class MyPostsView(ListView):
    paginate_by = 5
    model = Post
    template_name = 'post/my_posts.html'
    context_object_name = 'posts'

    def get_queryset(self):
        user = get_object_or_404(User, id=self.request.user.id)
        return Post.objects.filter(author__id__exact=user.id).order_by('-created')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all().order_by('name')
        return context


class MostCommentedPostsView(ListView):
    model = Post
    template_name = 'post/most_commented_posts.html'
    context_object_name = 'posts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all().order_by('name')
        return context


class PostsByTag(ListView):
    paginate_by = 5
    model = Post
    template_name = 'post/posts_by_tag.html'
    context_object_name = 'posts'

    def get_queryset(self):
        tag = get_object_or_404(Tag, slug=self.kwargs.get('tag_slug'))
        return Post.objects.filter(tags__in=[tag]).order_by('-created')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all().order_by('name')
        context['tag'] = get_object_or_404(Tag, slug=self.kwargs.get('tag_slug'))
        return context


# Serializacja
# JSON {"key": "value"} -> Python object

# Deserializacja
# Python object -> JSON {"key": "value"}

class UserSerializer(rf_serializers.ModelSerializer):
    class Meta:
        model = get_user_model()
        fields = ['id', 'username']


class PostSerializer(rf_serializers.ModelSerializer):
    author = UserSerializer()

    class Meta:
        model = Post
        fields = ['id', 'title', 'body', 'author', 'image']


class CommentSerializer(rf_serializers.ModelSerializer):
    post = PostSerializer()

    class Meta:
        model = Comment
        fields = ('post', 'id', 'author', 'text')


# ViewSets define the view behavior.
class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer


class CommentViewSet(viewsets.ModelViewSet):
    queryset = Comment.good_comment.all()
    serializer_class = CommentSerializer

post/templates/post/most_commented_posts.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load crispy_forms_tags %}
{% block title %}Most commented Posts{% endblock %}
{% block content %}
    <h2>Mostly commented Posts</h2><p></p>

    {% get_most_commented_posts 5 as most_commented_posts %}
    {% for post in most_commented_posts %}
       <h4 class="post_title"><a href="{% url 'post:post_detail' post.pk %}">{{ post.title|title }}</a></h4>
        <p>{{ post.created }} - <img class="image_micro" src="{{ post.author.profile.image.url }}"> <strong>{{ post.author }}</strong></p>

        <p>
        Tags: {% for tag in post.tags.all %}
        <a class="tag-link" href="{% url 'post:posts_by_tag' tag.slug %}">{{ tag.name }}</a>
            {% if not forloop.last %},{% endif %}
        {% empty %}There are no tags for this post
        {% endfor %}
        </p>

        <div class="post_image">
        {% if post.image %}
            <img src="/media/{{ post.image }}" class="image_mini">
        {% endif %}
        </div>
        <p></p>
        <p>{% autoescape off %}{{ post.body|truncatewords:60 }}{% endautoescape %}</p>
        <p>Comments: {{ post.comments.all.count }}</p>
    {% endfor %}

{% endblock %}

post/templates/post/my_posts.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ user.username }}'s Posts{% endblock %}
{% block content %}
    <h2>My Posts</h2><p></p>

    {% for post in page_obj %}
       <h4 class="post_title"><a href="{% url 'post:post_detail' post.pk %}">{{ post.title|title }}</a></h4>
        <p>{{ post.created }} - <img class="image_micro" src="{{ post.author.profile.image.url }}"> <strong>{{ post.author }}</strong></p>

        <p>
        Tags: {% for tag in post.tags.all %}
        <a class="tag-link" href="{% url 'post:posts_by_tag' tag.slug %}">{{ tag.name }}</a>
            {% if not forloop.last %},{% endif %}
        {% empty %}There are no tags for this post
        {% endfor %}
        </p>

        <div class="post_image">
        {% if post.image %}
            <img src="/media/{{ post.image }}" class="image_mini">
        {% endif %}
        </div>
        <p></p>
        <p>{% autoescape off %}{{ post.body|truncatewords:60 }}{% endautoescape %}</p>
        <p>Comments: {{ post.comments.all.count }}</p>
    {% endfor %}

    {% include "pagination.html" %}

{% endblock %}

post/templates/post/post-add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Add Post{% endblock %}
{% block content %}
    <h2>You can add new post here</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Create post</button>
    </form>
{% endblock %}

post/templates/post/post-del.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Delete {{ object.title|title }}{% endblock %}
{% block content %}
    <h2>Do you want to delete the post "{{ object.title|capfirst }}" ? </h2>
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit" >Yes</button>
        <button class="btn btn-warning" type="button" onclick="window.location.href='{% url 'post:post_list' %}'">Cancel</button>
    </form>
{% endblock %}

post/templates/post/post-detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ object.title|title }}{% endblock %}
{% block content %}
        <h2><b>"{{ object.title|title }}"</b></h2>

        <p>
        Tags: {% for tag in post.tags.all %}
        <a class="tag-link" href="{% url 'post:posts_by_tag' tag.slug %}">{{ tag.name }}</a>
            {% if not forloop.last %},{% endif %}
        {% empty %}There are no tags for this post
        {% endfor %}
        </p>

        {% if post.image %}
        <img class="img-fluid" src="{{ post.image.url }}">
        {% endif %}

        {% autoescape off %}
        {{ object.body|linebreaks }}
        {% endautoescape %}

        <div class="mb-5"><b>Author</b><h6>{{ object.author|title }}</h6></div>

        <form method="post" class="mb-2" id="add_comment">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success btn-sm">Add your comment</button>
        </form>

        <div id="new_comment" class="mb-4"></div>

        {% for comment in post.comments.all %}

            {% if not comment.hidden %}
            <div id="new_comment" class="mb-4">
                <h6 class="mt-4">Written: {{ comment.date_added }} by: {{ comment.author }}</h6>
                <p>{{ comment.text }}</p>
            </div>

            <p>
            {% if request.user == post.author %}
                <a class="hide-link" id="hide_comment" href="{% url 'post:hide_comment' pk=comment.pk %}">Hide comment</a>
            {% endif %}
            </p>
            {% endif %}

        {% empty %}
            <div id="new_comment" class="mb-4"></div>
            <p>Nobody has comment this post yet!</p>
        {% endfor %}

{% endblock %}

{% block javascript %}
    <script>
        $("#add_comment").on("submit", function (event) {
            event.preventDefault();
            console.log("add comment has been hit");
            // serialize the data for sending the form data.
            let serializedData = $(this).serialize();
            // make POST ajax call
            $.ajax({
                url: "{% url 'post:add_comment' pk=post.pk %}",
                method: 'POST',
                data: serializedData,
                success: function (response) {
                    let instance = JSON.parse(response["instance"]);
                    let fields = instance[0]["fields"];
                    $("#add_comment").trigger('reset');
                    let formatted_date_time = new Date(fields[('date_added')]);
                    let date = formatted_date_time.toLocaleDateString();
                    let time = formatted_date_time.toLocaleTimeString();
                    $("#new_comment").prepend(`<h6>Written: ${date} ${time} by: ${fields['author']}</h6><p>${fields['text']}</p>`);
                }
            })
        });
    </script>
{% endblock %}

post/templates/post/post-edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Edit:{{ object.title|title }}{% endblock %}
{% block content %}
    <h2>Post edition</h2>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" onclick="window.location.href='{% url 'post:post_list' %}'">Save</button>
    <button type="button" onclick="window.location.href='/'">Home page</button>
    </form>
{% endblock %}

post/templates/post/post-list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Latest Posts{% endblock %}
{% block content %}
    <h2>Latest Posts</h2><p></p>

    {% for post in page_obj %}
       <h4 class="post_title"><a href="{% url 'post:post_detail' post.pk %}">{{ post.title|title }}</a></h4>
        <p>{{ post.created }} - <img class="image_micro" src="{{ post.author.profile.image.url }}"> <strong>{{ post.author }}</strong></p>

        <p>
        Tags: {% for tag in post.tags.all %}
        <a class="tag-link" href="{% url 'post:posts_by_tag' tag.slug %}">{{ tag.name }}</a>
            {% if not forloop.last %},{% endif %}
        {% empty %}There are no tags for this post
        {% endfor %}
        </p>

        <div class="post_image">
        {% if post.image %}
            <img src="/media/{{ post.image }}" class="image_mini">
        {% endif %}
        </div>
        <p></p>
        <p>{% autoescape off %}{{ post.body|truncatewords:60 }}{% endautoescape %}</p>
        <p>Comments: {{ post.comments.all.count }}</p>
    {% endfor %}

    {% include "pagination.html" %}

{% endblock %}

post/templates/post/posts_by_tag.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Posts about {{ tag }}{% endblock %}
{% block content %}
    <h2>Posts about {{ tag }}</h2><p></p>

    {% for post in page_obj %}
       <h4 class="post_title"><a href="{% url 'post:post_detail' post.pk %}">{{ post.title|title }}</a></h4>
        <p>{{ post.created }} - <img class="image_micro" src="{{ post.author.profile.image.url }}"> <strong>{{ post.author }}</strong></p>

        <p>
        Tags: {% for tag in post.tags.all %}
        <a class="tag-link" href="{% url 'post:posts_by_tag' tag.slug %}">{{ tag.name }}</a>
            {% if not forloop.last %},{% endif %}
        {% empty %}There are no tags for this post
        {% endfor %}
        </p>

        <div class="post_image">
        {% if post.image %}
            <img src="/media/{{ post.image }}" class="image_mini">
        {% endif %}
        </div>
        <p></p>
        <p>{% autoescape off %}{{ post.body|truncatewords:60 }}{% endautoescape %}</p>
        <p>Comments: {{ post.comments.all.count }}</p>
    {% endfor %}

        {% include "pagination.html" %}

{% endblock %}

post/templates/post/search-post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Search{% endblock %}
{% block content %}
    <h2>Searching results:</h2><p></p>
    {% for post in object_list %}
       <h4 class="post_title"><a href="{% url 'post:post_detail' post.pk %}">{{ post.title|title }}</a></h4>
        <p>{{ post.created }} - <img class="image_micro" src="{{ post.author.profile.image.url }}"> <strong>{{ post.author }}</strong></p>

        <div class="post_image">
        {% if post.image %}
            <img src="/media/{{ post.image }}" class="image_mini">
        {% endif %}
        </div>
        <p></p>
        <p>{% autoescape off %}{{ post.body|truncatewords:30 }}{% endautoescape %}</p>
        <p>Total comments: {{ post.comments.all.count }}</p>
    {% endfor %}

{% endblock %}